In [1]:
import numpy as np

In [6]:
#n-dimensional homogeneous array
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
type(arr)

numpy.ndarray

In [8]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [9]:
a=np.array([1,2,3],dtype=str)
print(a)

['1' '2' '3']


In [10]:
len(a)

3

In [12]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
len(b)

2

In [14]:
#Get dimension of array
a.ndim

1

In [17]:
#Get a shape of numpy array
a.shape


(3,)

In [16]:
b.shape

(2, 3)

In [19]:
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('<U1')

In [21]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
#Get a specific element[r,c]
a[0,3]

4

In [23]:
a[1,0]

8

In [24]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
#Get a specific column
a[:,0]

array([1, 8])

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
a[0,3]=40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.full((3,3),50,dtype=float)

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [33]:
np.random.rand(4,4)

array([[0.3709576 , 0.5176964 , 0.8011829 , 0.07480191],
       [0.73203941, 0.84267668, 0.42913203, 0.53253023],
       [0.70844427, 0.14564852, 0.2911562 , 0.73217376],
       [0.4051172 , 0.47037425, 0.42675212, 0.94418271]])

In [35]:
np.random.randint(-4,1,size=(3,3))

array([[ 0, -4, -3],
       [-4, -4,  0],
       [ 0, -3, -1]])

In [36]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
a=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[12,12,12,12,12,12],
           [11,21,31,41,51,61],[13,24,34,44,54,63]
    ])

In [40]:
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [12 12 12 12 12 12]
 [11 21 31 41 51 61]
 [13 24 34 44 54 63]]


In [44]:
a[:3,-5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])